version: '4.6.0'

services:
  financas:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=produto
      - POSTGRESQL_USERNAME=teste
      - POSTGRESQL_PASSWORD=produtoTeste